---
# Generic Playbook to install and configure apache as an example

- name: Create domains document root
  file: path=/var/www/vhosts/{{ playbook.apache2.domain }} owner={{ playbook.apache2.owner }} group={{ playbook.apache2.group }} mode=0775 state=directory

- name: Add domains hostname file
  template: src=vhost.j2 dest={{ playbook.apache2.vhost_directory }}/{{ playbook.apache2.domain }}.conf

- name: Enable domain
  command: /usr/sbin/a2ensite {{ playbook.apache2.domain }}.conf
  notify: restart apache
  when: ansible_os_family == 'Debian'

- name: Restart apache
  service: name={{ playbook.apache2.apache }} state=restarted
