---
- name: unlink modules
  command:  /usr/sbin/a2dismod {{ item }}
  with_items:
    - "mpm_*"
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '14.04'

- name: copy module configuration templates
  template: src=apache24/mods/{{ item }}.conf.j2 dest=/etc/apache2/mods-available/{{ item }}.conf owner=root group=root
  with_items: playbook.apache2.apache_modules.v247_conf
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '14.04'
  ignore_errors: yes

- name: Enable apache modules for Debian based
  command: /usr/sbin/a2enmod {{ item }}
  with_items: playbook.apache2.apache_modules.v22
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '12.04'

- name: Enable apache modules for Debian based
  command: /usr/sbin/a2enmod {{ item }}
  with_items: playbook.apache2.apache_modules.v247
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '14.04'
  notify: restart apache
