---
# Generic Playbook to install and configure apache as an example

- name: Install PHP and packages
  apt: pkg={{ item }} state=installed update_cache=true
  with_items: playbook.phpmyadmin.packages
  when: ansible_os_family == 'Debian'

- name: Create htpasswd
  command: htpasswd -b -c /etc/phpmyadmin/phpmyadmin-htpasswd "{{ playbook.phpmyadmin.user }}" "{{ playbook.phpmyadmin.passwd }}"

- name: copy .phpmyadminpass template
  template: src=phpmyadminpass.j2 dest=/root/.phpmyadminpass owner=root group=root mode=0400
  when: ansible_os_family == 'Debian'

- name: copy "{{ansible_os_family}}.apache.conf" template
  template: src="{{ansible_os_family}}_apache.conf.j2" dest=/etc/phpmyadmin/apache.conf owner=root group=root mode=0644
  when: ansible_os_family == 'Debian'

- name: copy "{{ansible_os_family}}_config.inc.php" template
  template: src="{{ansible_os_family}}_config.inc.php.j2" dest=/etc/phpmyadmin/config.inc.php owner=root group=root mode=0644
  when: ansible_os_family == 'Debian'

