---
#- include_vars: "{{ ansible_os_family }}.yml"

- name: Install holland pkgs on Redhat base
  yum: name={{item}} state=present
  with_items:
  - MySQL-python
  - holland-common
  when: ansible_os_family == 'RedHat'

- name: Include default.yml on Debian
  include: default.yml
  when: ansible_os_family == 'Debian'

- name: Install holland pgs on Debian base
  apt: name=python-mysqldb state=present
  when: ansible_os_family == 'Debian'

- name: Download .deb files for local install
  copy: src=holland-common_{{holland_version}}_all.deb dest=/tmp/holland-common_{{holland_version}}_all.deb
  when: ansible_os_family == 'Debian'
  register: deb_common_dl

- name: Install .deb file
  dpkg: deb=/tmp/holland-common_{{holland_version}}_all.deb state=present
  when: ansible_os_family == 'Debian' and deb_common_dl|changed
  register: deb_common_installed

- name: Cleanup .deb file
  file: dest=/tmp/holland-common_{{holland_version}}_all.deb state=absent
  when: ansible_os_family == 'Debian' and deb_common_installed|changed


